### ISSUE TITLE
About python wrapper

### ISSUE THREAD

**Issue by liaocyintl-deprecated** [CansenJIANG/deepMatchingGUI#1]
Hi, thanks for supporting the code.
I want to use the deepMatching python wrapper.
But the 'make python' seems doesn't work.
How can I fix it?
Thank you very much!

**Comment by iimmortall** [comment]
Hi, can you use the deepmatching C++ wrapper? if not , you should install caff (cpu) platform.

**Comment by liaocyintl-deprecated** [comment]
Get it. Thank you very much!

**Comment by CansenJIANG** [comment]
Hi,

Yes, I think I was using it. In the worst case, you can compile the code,
and just call the executable file, it should work.


Best regards,
Cansen

Cansen JIANG
Phd, Université de Bourgogne, France
Tel:+33 07 82 55 26 99
E-mail:cansenjiang@gmail.com
